### ISSUE TITLE
Put AI in hosts place?

### ISSUE THREAD

**Issue by Evanito** [DrNewbie/DedicatedServer#1]
Playing with 3 players is kind if a bummer, can you put a bot in the hosts place?

**Comment by DrNewbie** [comment]
Host (you) handle everything, include bot, so we can't ask those AI to handle server, but you can increase bot amount (https://youtu.be/4PClMLaPjq4).

**Comment by Evanito** [comment]
I see you made the script to increase the bot amount. Seeing as that is impossible for me to access, could you merge some of it into this dedicated server?

After host is locked away, put a single bot in his place so the gang doesn't lose too much firepower?

**Comment by DrNewbie** [comment]
I think that's another work.
