### ISSUE TITLE
Make in game settings instead of .txt

### ISSUE THREAD

**Issue by Evanito** [DrNewbie/DedicatedServer#5]
Currently, the settings file is rather confusing, as it is on long line. How about adding options via an in game menu for certain toggle able options? Long text options would probably need to stay in Settings.txt but things such as which maps are in rotation and other "checkbox" options should be usable in a menu.

**Comment by DrNewbie** [comment]
You don't need to change it repeatedly seem you're Dedicated Server so go to edit ''DedicatedServer.Default_Settings''(https://git.io/vix58) and use ''Reset'' (Mod Menu-->Dedicated Server).
