### ISSUE TITLE
Allow random contract choosing

### ISSUE THREAD

**Issue by Evanito** [DrNewbie/DedicatedServer#7]
I see you are the maker of the "Choose random contract" mod

Can we get support for that in this mod?

Right now it plays Hoxton Breakout over and over.

**Comment by DrNewbie** [comment]
I think that should be ''plugin'' that add\change\modify by user.
Anyway, if you don't have those DLC, then yes, I guess you will run Hoxton Breakout over and over. (https://git.io/vixdq)
